---
version: '2'
services:
  # watcher application (websocket bridge between browser and HW)
  watcher:
    environment:
      DEBUG: 1
      LED_OFF: 1
    volumes:
      - $PWD/watcher/watcher:/src
