FROM python:2.7

RUN mkdir -p /src/app
VOLUME ["/src/app"]
WORKDIR "/src/app"
ENTRYPOINT ["uwsgi"]

RUN pip install \
    Django==1.7.4 \
    Pillow==2.7.0 \
    django-extensions==1.5.0 \
    djangorestframework==3.0.5 \
    uwsgi==2.0 \
    PyYAML==3.11 \
    ipdb \
    ipython \
    tipi
